baseURL = 'https://mortezaazizi.com'
languageCode = 'en-us'
title = 'Morteza Azizi'
theme = 'PaperMod'

[permalinks]
  pages = "/:slug"

[params]
    defaultTheme = "auto"
    ShowBreadCrumbs = true
    ShowToc = true

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
