baseURL = "https://www.mortezaazizi.com/"
languageCode = 'en-us'
title = 'Morteza Azizi'
theme = 'hugo-coder'

[params]
    defaultTheme = "auto"
    ShowBreadCrumbs = true
    ShowToc = true
    mainSections = ["posts"]
    customCSS = ["css/custom.css"]

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
        
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2
