baseURL = 'https://blog-39a.pages.dev'
languageCode = 'en-us'
title = 'Morteza Azizi'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    ShowBreadCrumbs = true
    ShowToc = true

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1
